# Generated by Django 4.1.4 on 2022-12-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chat_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
